[project]
name = "24-ztm-katowice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gtfs-kit>=10.3.1",
    "polars>=1.33.1",
    "tqdm>=4.67.1",
]
